const stateNames = {
  ak: "Alaska",
  al: "Alabama",
  ar: "Arkansas",
  az: "Arizona",
  ca: "California",
  co: "Colorado",
  ct: "Connecticut",
  dc: "District Of Columbia",
  de: "Delaware",
  fl: "Florida",
  ga: "Georgia",
  hi: "Hawaii",
  ia: "Iowa",
  id: "Idaho",
  il: "Illinois",
  in: "Indiana",
  ks: "Kansas",
  ky: "Kentucky",
  la: "Louisiana",
  ma: "Massachusetts",
  md: "Maryland",
  me: "Maine",
  mi: "Michigan",
  mn: "Minnesota",
  mo: "Missouri",
  ms: "Mississippi",
  mt: "Montana",
  nc: "North Carolina",
  nd: "North Dakota",
  ne: "Nebraska",
  nh: "New Hampshire",
  nj: "New Jersey",
  nm: "New Mexico",
  nv: "Nevada",
  ny: "New York",
  oh: "Ohio",
  ok: "Oklahoma",
  or: "Oregon",
  pa: "Pennsylvania",
  ri: "Rhode Island",
  sc: "South Carolina",
  sd: "South Dakota",
  tn: "Tennessee",
  tx: "Texas",
  ut: "Utah",
  va: "Virginia",
  vt: "Vermont",
  wa: "Washington",
  wi: "Wisconsin",
  wv: "West Virginia",
  wy: "Wyoming",
};
for (abbreviation in stateNames) {
  let stateImage = document.getElementsByClassName(abbreviation)[0];
  stateImage.addEventListener("click", function (event) {
    const stateNames = {
      ak: "Alaska",
      al: "Alabama",
      ar: "Arkansas",
      az: "Arizona",
      ca: "California",
      co: "Colorado",
      ct: "Connecticut",
      dc: "District_Of_Columbia",
      de: "Delaware",
      fl: "Florida",
      ga: "Georgia",
      hi: "Hawaii",
      ia: "Iowa",
      id: "Idaho",
      il: "Illinois",
      in: "Indiana",
      ks: "Kansas",
      ky: "Kentucky",
      la: "Louisiana",
      ma: "Massachusetts",
      md: "Maryland",
      me: "Maine",
      mi: "Michigan",
      mn: "Minnesota",
      mo: "Missouri",
      ms: "Mississippi",
      mt: "Montana",
      nc: "North_Carolina",
      nd: "North_Dakota",
      ne: "Nebraska",
      nh: "New_Hampshire",
      nj: "New_Jersey",
      nm: "New_Mexico",
      nv: "Nevada",
      ny: "New_York",
      oh: "Ohio",
      ok: "Oklahoma",
      or: "Oregon",
      pa: "Pennsylvania",
      ri: "Rhode_Island",
      sc: "South_Carolina",
      sd: "South_Dakota",
      tn: "Tennessee",
      tx: "Texas",
      ut: "Utah",
      va: "Virginia",
      vt: "Vermont",
      wa: "Washington",
      wi: "Wisconsin",
      wv: "West_Virginia",
      wy: "Wyoming",
    };
    window.location.href = `${stateNames[event.target.classList[0]]}.html`;
  });
  stateImage.addEventListener("mouseover", function (e) {
    const stateNames = {
      ak: "Alaska",
      al: "Alabama",
      ar: "Arkansas",
      az: "Arizona",
      ca: "California",
      co: "Colorado",
      ct: "Connecticut",
      dc: "District_Of_Columbia",
      de: "Delaware",
      fl: "Florida",
      ga: "Georgia",
      hi: "Hawaii",
      ia: "Iowa",
      id: "Idaho",
      il: "Illinois",
      in: "Indiana",
      ks: "Kansas",
      ky: "Kentucky",
      la: "Louisiana",
      ma: "Massachusetts",
      md: "Maryland",
      me: "Maine",
      mi: "Michigan",
      mn: "Minnesota",
      mo: "Missouri",
      ms: "Mississippi",
      mt: "Montana",
      nc: "North_Carolina",
      nd: "North_Dakota",
      ne: "Nebraska",
      nh: "New_Hampshire",
      nj: "New_Jersey",
      nm: "New_Mexico",
      nv: "Nevada",
      ny: "New_York",
      oh: "Ohio",
      ok: "Oklahoma",
      or: "Oregon",
      pa: "Pennsylvania",
      ri: "Rhode_Island",
      sc: "South_Carolina",
      sd: "South_Dakota",
      tn: "Tennessee",
      tx: "Texas",
      ut: "Utah",
      va: "Virginia",
      vt: "Vermont",
      wa: "Washington",
      wi: "Wisconsin",
      wv: "West_Virginia",
      wy: "Wyoming",
    };
    const combos = {
      al: ["al-fl", "al-ga", "al-ms", "al-tn"],
      fl: ["al-fl", "fl-ga"],
      ga: ["al-ga", "fl-ga", "ga-nc", "ga-sc", "ga-tn"],
      ms: ["al-ms", "ar-ms", "la-ms", "ms-tn"],
      tn: ["al-tn","ar-tn","ga-tn","ky-tn","mo-tn","ms-tn","nc-tn","tn-va",],
      ar: ["ar-la", "ar-mo", "ar-ms", "ar-ok", "ar-tn", "ar-tx"],
      la: ["ar-la", "la-ms", "la-tx"],
      mo: ["ar-mo","ia-mo","il-mo","ks-mo","ky-mo","mo-ne","mo-ok","mo-tn",],
      ok: ["ar-ok", "co-ok", "ks-ok", "mo-ok", "nm-ok", "ok-tx"],
      tx: ["ar-tx", "la-tx", "nm-tx", "ok-tx"],
      az: ["az-ca", "az-nm", "az-nv", "az-ut"],
      ca: ["az-ca", "ca-nv", "ca-or"],
      nm: ["az-nm", "co-nm", "nm-ok", "nm-tx"],
      nv: ["az-nv", "ca-nv", "id-nv", "nv-or", "nv-ut"],
      ut: ["az-ut", "co-ut", "id-ut", "nv-ut", "ut-wy"],
      or: ["ca-or", "id-or", "nv-or", "or-wa"],
      co: ["co-ks", "co-ne", "co-nm", "co-ok", "co-ut", "co-wy"],
      ks: ["co-ks", "ks-mo", "ks-ne", "ks-ok"],
      ne: ["co-ne", "ia-ne", "ks-ne", "mo-ne", "ne-sd", "ne-wy"],
      wy: ["co-wy", "id-wy", "mt-wy", "ne-wy", "sd-wy", "ut-wy"],
      ct: ["ct-ma", "ct-ny", "ct-ri"],
      ma: ["ct-ma", "ma-nh", "ma-ny", "ma-ri", "ma-vt"],
      ny: ["ct-ny", "ma-ny", "nj-ny", "ny-pa", "ny-vt"],
      ri: ["ct-ri", "ma-ri"],
      dc: ["dc-md", "dc-va"],
      md: ["dc-md", "de-md", "md-pa", "md-va", "md-wv"],
      va: ["dc-va", "ky-va", "md-va", "nc-va", "tn-va", "va-wv"],
      de: ["de-md", "de-nj", "de-pa"],
      nj: ["de-nj", "nj-ny", "nj-pa"],
      pa: ["de-pa", "md-pa", "nj-pa", "ny-pa", "oh-pa", "pa-wv"],
      nc: ["ga-nc", "nc-sc", "nc-tn", "nc-va"],
      sc: ["ga-sc", "nc-sc"],
      ia: ["ia-il", "ia-mn", "ia-mo", "ia-ne", "ia-sd", "ia-wi"],
      il: ["ia-il", "il-in", "il-ky", "il-mo", "il-wi"],
      mn: ["ia-mn", "mn-nd", "mn-sd", "mn-wi"],
      sd: ["ia-sd", "mn-sd", "mt-sd", "nd-sd", "ne-sd", "sd-wy"],
      wi: ["ia-wi", "il-wi", "mi-wi", "mn-wi"],
      id: ["id-mt", "id-nv", "id-or", "id-ut", "id-wa", "id-wy"],
      mt: ["id-mt", "mt-nd", "mt-sd", "mt-wy"],
      wa: ["id-wa", "or-wa"],
      in: ["il-in", "in-ky", "in-mi", "in-oh"],
      ky: ["il-ky", "in-ky", "ky-mo", "ky-oh", "ky-tn", "ky-va", "ky-wv"],
      mi: ["in-mi", "mi-oh", "mi-wi"],
      oh: ["in-oh", "ky-oh", "mi-oh", "oh-pa", "oh-wv"],
      wv: ["ky-wv", "md-wv", "oh-wv", "pa-wv", "va-wv"],
      nh: ["ma-nh", "me-nh", "nh-vt"],
      vt: ["ma-vt", "nh-vt", "ny-vt"],
      me: ["me-nh"],
      nd: ["mn-nd", "mt-nd", "nd-sd"],
    };
    const stateCode = e.target.classList[0]
    const stateCombos = combos[stateCode];
    for (let borderCode of stateCombos) {
      document
        .getElementsByClassName(borderCode)[0]
        .classList.add("highlight-border");
    }

    e.target.classList.add('highlight-state')
    document.getElementById('hover-name').innerHTML = stateNames[stateCode]
    const death_data = JSON.parse(document.getElementById('death_data').innerHTML)[stateNames[stateCode]]
    document.getElementById('hover-population').innerHTML = death_data['population']
    document.getElementById('hover-total').innerHTML = death_data['total_deaths']

  });
  stateImage.addEventListener('mouseout', function(e){
    const combos = {
      al: ["al-fl", "al-ga", "al-ms", "al-tn"],
      fl: ["al-fl", "fl-ga"],
      ga: ["al-ga", "fl-ga", "ga-nc", "ga-sc", "ga-tn"],
      ms: ["al-ms", "ar-ms", "la-ms", "ms-tn"],
      tn: ["al-tn","ar-tn","ga-tn","ky-tn","mo-tn","ms-tn","nc-tn","tn-va",],
      ar: ["ar-la", "ar-mo", "ar-ms", "ar-ok", "ar-tn", "ar-tx"],
      la: ["ar-la", "la-ms", "la-tx"],
      mo: ["ar-mo","ia-mo","il-mo","ks-mo","ky-mo","mo-ne","mo-ok","mo-tn",],
      ok: ["ar-ok", "co-ok", "ks-ok", "mo-ok", "nm-ok", "ok-tx"],
      tx: ["ar-tx", "la-tx", "nm-tx", "ok-tx"],
      az: ["az-ca", "az-nm", "az-nv", "az-ut"],
      ca: ["az-ca", "ca-nv", "ca-or"],
      nm: ["az-nm", "co-nm", "nm-ok", "nm-tx"],
      nv: ["az-nv", "ca-nv", "id-nv", "nv-or", "nv-ut"],
      ut: ["az-ut", "co-ut", "id-ut", "nv-ut", "ut-wy"],
      or: ["ca-or", "id-or", "nv-or", "or-wa"],
      co: ["co-ks", "co-ne", "co-nm", "co-ok", "co-ut", "co-wy"],
      ks: ["co-ks", "ks-mo", "ks-ne", "ks-ok"],
      ne: ["co-ne", "ia-ne", "ks-ne", "mo-ne", "ne-sd", "ne-wy"],
      wy: ["co-wy", "id-wy", "mt-wy", "ne-wy", "sd-wy", "ut-wy"],
      ct: ["ct-ma", "ct-ny", "ct-ri"],
      ma: ["ct-ma", "ma-nh", "ma-ny", "ma-ri", "ma-vt"],
      ny: ["ct-ny", "ma-ny", "nj-ny", "ny-pa", "ny-vt"],
      ri: ["ct-ri", "ma-ri"],
      dc: ["dc-md", "dc-va"],
      md: ["dc-md", "de-md", "md-pa", "md-va", "md-wv"],
      va: ["dc-va", "ky-va", "md-va", "nc-va", "tn-va", "va-wv"],
      de: ["de-md", "de-nj", "de-pa"],
      nj: ["de-nj", "nj-ny", "nj-pa"],
      pa: ["de-pa", "md-pa", "nj-pa", "ny-pa", "oh-pa", "pa-wv"],
      nc: ["ga-nc", "nc-sc", "nc-tn", "nc-va"],
      sc: ["ga-sc", "nc-sc"],
      ia: ["ia-il", "ia-mn", "ia-mo", "ia-ne", "ia-sd", "ia-wi"],
      il: ["ia-il", "il-in", "il-ky", "il-mo", "il-wi"],
      mn: ["ia-mn", "mn-nd", "mn-sd", "mn-wi"],
      sd: ["ia-sd", "mn-sd", "mt-sd", "nd-sd", "ne-sd", "sd-wy"],
      wi: ["ia-wi", "il-wi", "mi-wi", "mn-wi"],
      id: ["id-mt", "id-nv", "id-or", "id-ut", "id-wa", "id-wy"],
      mt: ["id-mt", "mt-nd", "mt-sd", "mt-wy"],
      wa: ["id-wa", "or-wa"],
      in: ["il-in", "in-ky", "in-mi", "in-oh"],
      ky: ["il-ky", "in-ky", "ky-mo", "ky-oh", "ky-tn", "ky-va", "ky-wv"],
      mi: ["in-mi", "mi-oh", "mi-wi"],
      oh: ["in-oh", "ky-oh", "mi-oh", "oh-pa", "oh-wv"],
      wv: ["ky-wv", "md-wv", "oh-wv", "pa-wv", "va-wv"],
      nh: ["ma-nh", "me-nh", "nh-vt"],
      vt: ["ma-vt", "nh-vt", "ny-vt"],
      me: ["me-nh"],
      nd: ["mn-nd", "mt-nd", "nd-sd"],
    };
    const stateCombos = combos[e.target.classList[0]];
    for (let borderCode of stateCombos) {
      document
        .getElementsByClassName(borderCode)[0]
        .classList.remove("highlight-border");
    }
    e.target.classList.remove('highlight-state')
  })
}
